### ISSUE TITLE
Analytics is undefined

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/AppCenter-SDK-React-Native#173]
Hi guys,

I'm getting the following error when I try to import the sdk: `Analytics is undefined`

<img width="397" alt="react-native error" src="https://user-images.githubusercontent.com/2154886/33344914-86dc1bb6-d458-11e7-9673-9f6245981d01.png">

Thanks in advance, Nicholls

**Comment by khriztianmoreno** [comment]
The steps that were carried out were:

1. Add App Center SDK modules
```json
    "appcenter-analytics": "1.0.1",
    "appcenter-crashes": "1.0.1",
    "appcenter-push": "1.0.1",
    "react": "16.0.0",
    "react-native": "0.50.3",
```
2. Link the plugins to the React Native app by using the react-native link command.
3. Pod File
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bevyUp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bevyUp
  pod 'AppCenter/Push', '~> 1.0.1'
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

end
```

**Comment by guperrot** [comment]
Hi, it seems you are calling `AppCenterReactNativeAnalytics.isEnabled()` instead of `Analaytics.isEnabled()`, can you copy the import lines and the javascript code lines using our APIs?

**Comment by khriztianmoreno** [comment]
```js
import Analytics from 'appcenter-analytics';

...

async componentDidMount() {
    const component = this;

    try {
      const analyticsEnabled = await Analytics.isEnabled();
      component.setState({ analyticsEnabled });
    } catch (error) {
      console.warn("Error", error);
    }
  }
```

**Comment by dhei** [comment]
Hi @khriztianmoreno, which option did you choose during `react-native link` of Analytics, `Enable Automatically` or `Enable in JavaScript`? If you choose to enabled in JavaScript, did you `await Analytics.setEnabled(true)` in JS code?

**Comment by khriztianmoreno** [comment]
@dhei  I am tried both options(Automatically, Enable in JavaScript) and result is same, right now what I'm looking for is to track a specific event through javascript, What would be the correct way?

**Comment by dhei** [comment]
@khriztianmoreno The right way to track event in JS is to call `Analytics.trackEvent("myEvent");` per [App Center documentation](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/react-native#custom-events). I don't see any problem in your `componentDidMount` JS code. 

I am not sure how to repro your error. In order to troubleshoot this error, can you do the following:
1. Do you see your custom events showing up on App Center portal?
2. Turn on the App Center Verbose logging (follow [this documentation](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/react-native#adjust-the-log-level) if you are not sure how to turn on verbose logging)? Do you see AppCenter Analytics service registered successfully with App Center backend in verbose log?

**Comment by dhei** [comment]
@khriztianmoreno This error can happen if `appcenter-analytics` is not linked correctly during `react-native link`. Do you see any error in `react-native link`? Can you check your ios `AppDelegate.m`, do you see `[AppCenterReactNativeAnalytics registerWithInitiallyEnabled:]` call ?

**Comment by khriztianmoreno** [comment]
Creating a project from scratch everything works correctly, I do not really know what is due, we can close this issue, thanks @dhei  for the help.

**Comment by ldco2016** [comment]
You closed this and two years later here I am having a similar issue:

https://github.com/microsoft/appcenter-sdk-react-native/issues/666
