### ISSUE TITLE
Firebase-messaging reintroduced with old version

### ISSUE THREAD

**Issue by aaroncmoore** [Microsoft/AppCenter-SDK-React-Native#365]
I ran into this issue tonight while building my react native app with firebase:

Failed to capture snapshot of input files for task ':appcenter-push:compileReleaseAidl' property 'importDirs' during up-to-date check.
> The library com.google.firebase:firebase-iid is being requested by various other libraries at [[16.2.0,16.2.0]], but resolves to 16.0.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

Confused what or how appcenter-push was creating this issue I did some digging for updates and found this:

https://github.com/Microsoft/AppCenter-SDK-React-Native/pull/341/files/6be2c0d454a33dc39e560538ebd445a23d0d43d0

firebase-messaging was re-introduced into appcenter with:
+    implementation 'com.google.firebase:firebase-core:16.0.1'
+    implementation 'com.google.firebase:firebase-messaging:17.0.0'

The version of messaging is not up to date (17.1.0 is the up to date version).  Firebase messaging 17.0.0 uses firebase-iid 16.0.0, while firebase 17.1.0 uses firebase-iid 16.2.0, thus creating the conflict.

Would it be possible to use firebase-messaging 17.1.0?  Is there a reason the new version was released with an older firebase version?

The steps to re-produce this is easy enough.  Create a project using 17.1.0 and then compile with appcenter 1.7 and this conflict should appear.

For now I have downgraded to appcenter 1.6 to resolve this issue for my builds but I'd prefer to not have to do this long term.

Thanks!

**Comment by dhei** [comment]
Hey @aaroncmoore,

Thanks for getting in touch. We found the issue that is caused by Google Firebase library dependencies.

The issue is the 'com.google.firebase:firebase-core:16.0.1' takes a dependency on 'com.google.firebase:firebase-iid:16.0.0' while 'com.google.firebase:firebase-messaging:17.1.0' takes a dependency on 'com.google.firebase:firebase-iid:16.2.0'. Starting from 'com.google.gms:google-services:3.3.0', Google is requiring [strict version matching](https://developers.google.com/android/guides/versioning#google_services_plugin). For more information, you can check out the [May 2nd 2018 release notes of Google Services Gradle Plugin](https://developers.google.com/android/guides/releases#may_2_2018) explaining this change.

> In order to support this change in versioning, the Google Services Gradle plugin has been updated. Starting with version 3.3.0, this plugin checks for compatible versions of Google Play services and Firebase libraries.

It really depends on Firebase fixes this mismatched dependency on their side. Before Firebase fixes this issue on their side, there are a few possible workarounds to avoid the gradle build error:

(1) Disable the strict version check. Simply adding the following line to app/build.gralde:

```gradle
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

(2) Stay on `com.google.firebase:firebase-messaging:17.0.0` instead of  `com.google.firebase:firebase-messaging:17.1.0`.

(3) Downgrade `classpath 'com.google.gms:google-services:4.0.1'` to a version prior to 3.3.0 to avoid strict version matching.

Thanks
Di

**Comment by guperrot** [comment]
Also firebase messaging 17.0.0 works with core 16.0.1, we tested that setup in multiple applications.

**Comment by aaroncmoore** [comment]
Thank you dhei for your response.  

I am fairly certain it is not 'com.google.firebase:firebase-core:16.0.1' that requires the 'com.google.firebase:firebase-iid:16.0.0' as I've not had a problem running with 'com.google.firebase:firebase-messaging:17.1.0' since June.  Also, react-native-firebase also requires both versions of firebase to be current for version 4.3, which downgrading to 'com.google.firebase:firebase-messaging:17.0.0' breaks react-native-firebase for the same reason that we see here.

Regardless, disabling version check does solve the issue, if only temporarily.  Overall strict versioning has made me far more aware of project dependencies than before, which I guess is its purpose.

**Comment by guperrot** [comment]
firebase-core 16.0.1 is incompatible with firebase-messaging 17.1.0 or 17.3.0 when declared from a lib according to the plugin that checks strict version.

However if those same versions are used directly from an app that don't use any libs, then the warning is gone.

We however cannot change our SDK instructions to add dependencies directly in the app (and remove them from the lib) as it would be a breaking change for people that already have the native SDK and just update.

Since this issue impacts only a few users, we recommend using `com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true` and override the dependencies in the app to use latest if you need the latest, this is now the official work around for App Center SDK.

When Firebase decides to eventually update firebase core to match messaging, we can update our native SDK dependencies.

**Comment by guperrot** [comment]
Version 1.10.0 uses the latest Firebase version as of today.
