### ISSUE TITLE
Question about react-native link

### ISSUE THREAD

**Issue by iAladdin** [microsoft/appcenter-sdk-react-native#438]
Hi, 

I try to use this package with CI, and how to preconfig for react-native link. The command line function will prompt a question:

Android App Secret is already set in android/app/src/main/assets/appcenter-config.json
? For the Android app, should user tracking be enabled automatically? (Use arrow keys)
❯ Enable Automatically
  Enable in JavaScript

how to auto select or preconfig for react-native link? 

thank you!

**Comment by ElektrojungeMS** [comment]
Hi @iAladdin,

thanks for getting in touch. Unfortunately, this is not possible today.
You need to run `react-native link` locally, answer all the prompts and check in the integrated SDK.

We are currently tracking this as a feature request and the more people ask for it, the sooner we get to change it, so please comment, +1 or something.

**Comment by iAladdin** [comment]
Hi @ElektrojungeMS ,

Currently, I try to use `printf '\n\n\n' | react-native link` to automatic answer prompts , but it's not a good way I think.

If you or your team can share your CI experiences, that would be great! 

Thank you again!

**Comment by ElektrojungeMS** [comment]
@iAladdin,

That's a way to hack it but would recommend doing it.

For your problem, our recommendation is what I outlined above. It has been a rare feature ask to remove the prompts from the react native link integration, that's why I'm asking for feedback and +1 if you'd be interested in this change – the more people request it, the higher it will be on the priority list.

Now, about CI experiences/recommendations, what are your exact questions? We do have our own [blog post about CI/CD 101](https://blogs.msdn.microsoft.com/vsappcenter/mobile_cicd_101/) and then there's a few resources by other people on how to to CI/CD with App Center for RN, e.g. https://medium.com/react-native-training/setup-continuous-integration-with-react-native-50ad2f6145f4.

**Comment by ElektrojungeMS** [comment]
Hey,
We haven't heard from you for some time. I'm closing this issue but feel free to get in touch or reopen it any time.

Best,
Benjamin

**Comment by ElektrojungeMS** [comment]
Leaving this open as this is a feature request.

**Comment by clpolet** [comment]
@Hreacon thanks for your interest in this feature request, counting you in ;).

**Comment by iAladdin** [comment]
Hey guys,

I have to report about my solution for now:

when I run my CI task with gitlab CI, it's run task with non-interactive flag, so every prompt automatic answer with yes( from the result, I guess it pass yes automatically)

when I run react-native link on development environment, I can just run with `echo|react-native link`, it works for me.

But I think if there is a config file can change it after first time, it'll be a better solution for this.

**Comment by guperrot** [comment]
Removing prompt was released in May: https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/2.0.0.
