### ISSUE TITLE
https://github.com/Microsoft/AppCenter-SDK-React-Native/issues class not found 

### ISSUE THREAD

**Issue by waltershub** [Microsoft/AppCenter-SDK-React-Native#521]
### **Description**

the app won't build unless the line is is commented out

```js
 [MSAppCenter setUserId:userId];
```

### **Repro Steps**

1. run yarn upgrade
2.build 

### **Details**

1. Which version of the App Center SDK are you using?
   "appcenter": "^1.9.0",
    "appcenter-analytics": "^1.9.0",
    "appcenter-crashes": "^1.9.0",
2. Which OS version did you experience the issue on?
  iOS 12
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Google Pixel 2 emulator, iPhone X physical device
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`

Place output here

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Place output here

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:

**Comment by dhei** [comment]
Hi @waltershub,

Thanks for getting in touch.

I noticed you're not pinning appcenter modules in package.json.

The error is likely caused by not pinning appcenter modules in **package.json** (the caret `^` in `"appcenter": "^1.9.0"`) and appcenter modules not up-to-date with native iOS dependencies in **Podfile**. Please see https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/449 which explains the details of this problem and how to solve it.

Note that we shipped **UserId** support recently in our latest release https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/tag/1.12.0. 

I recommend upgrade all your appcenter modules (appcenter/appcenter-analytics/appcenter-crashes/etc) to v1.12.0 and then make sure execute `react-native link`. You may check out our recommendation on [How to update React Native SDK to the latest version](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#how-to-update-react-native-sdk-to-the-latest-version).

**Comment by waltershub** [comment]
@dhei thanks we downgraded to 1.11.0 and removed the ^ and everything works great
