### ISSUE TITLE
Add an API to see if pushes are enabled in the native platform

### ISSUE THREAD

**Issue by janpieterz** [microsoft/appcenter-sdk-react-native#622]
### **Description**

It'd be great if there was an API  that would return if push is enabled in the platform (blocked or not). React Native doesn't have this in it's Android permissions. This would allow us to have more grip on the stability of the push channel for communication.

**Comment by bobber205** [comment]
Anyone have insight if this is possible or not? I agree it'd be a dope feature but it may not be possible due to that setting being stored maybe locally on the phone?

**Comment by guperrot** [comment]
This is possible to some degree. On iOS you have to test if alerts are enabled (as you could also push audio/badge). On Android it depends on the Android version. Before Android 4.3 it will just says always enabled (true) because the API didn't exist back then. And starting from Android 8, you probably have to test settings on the specific channel used by Firebase to see if that one is enabled by the user.

**Comment by jwargo** [comment]
@janpieterz thank you for the suggestion, I'll add this to our list of feature requests. 

FYI - we created a specific repo for tracking feature requests and to publish our implementation plans, you can find our roadmap there too: https://github.com/Microsoft/appcenter. Vote for your favorite features there.

**Comment by AnastasiaKubova** [comment]
I'm closing this issue since [App Center Push has been removed from the SDK in 4.0.0](https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/CHANGELOG.md#version-400).
