### ISSUE TITLE
AppCenterReactNativePush undefined in Android

### ISSUE THREAD

**Issue by codeithuman** [microsoft/appcenter-sdk-react-native#720]
It appears that `AppCenterReactNativePush` is `undefined` in my Android React Native application. The issue is related to this [line in](https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/appcenter-push/Push.js#L6) Push.js and where ever `AppCenterReactNativePush` is called, for example [here](https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/appcenter-push/Push.js#L16).

In my root component `/src/screens/App.tsx` I am calling the following at the bottom of the file:

```
async function isPushEnabled() {
  try {
    return await Push.isEnabled()
  }
  catch (error) {
    console.log(`error: ${error}`)
  }
  finally {
    console.log('done')
  }
}

isPushEnabled().then((isPushEnabled) => { console.log({isPushEnabled})})
```

`isPushEnabled` logs `undefined` and I get the error `error: TypeError: Cannot read property 'isEnabled' of undefined`.

I worked through the setup documentation several times, but continue to get the same error. I'm thinking there is an issue related to App Center and Android, but I am not sure how to debug it further. 

Thanks in advance for your help!

**Comment by codeithuman** [comment]
In addition, I cannot get the DemoApp running, https://github.com/microsoft/appcenter-sdk-react-native/tree/develop/DemoApp.

**Comment by annakocheshkova** [comment]
Hi there @codeithuman I don't think the issue is related to this: this statement just retrieves the React module and it's exactly the same in all the modules.
The simplest answer is that there's `import Push from 'appcenter-push';` missing, but I guess that's not the case here.

So probably something went wrong at module installation stage.
- Are you able to use other App Center modules?
- This happens only on Android? 
- Were there any errors/warning during plugin installation?

And also, please include the environment details :)

**Comment by codeithuman** [comment]
Thanks for the quick replies. Unforchanetly I need to start work on another priority and will close this issue for now so it is not lingering.
