### ISSUE TITLE
AppCenter build failed for iOS React native 

### ISSUE THREAD

**Issue by pratius** [microsoft/appcenter-sdk-react-native#978]
### **Description**

I'm trying to integrate AppCenter build for iOS and Android apps. But I'm facing an issue while integrating the build for iOS.
Please help me to integrate a build pipeline. I have already wasted one week on these issues to resolve.

**Issues:-** 

ARCHIVE FAILED 

The following build commands failed:
	CompileC /Users/runner/Library/Developer/Xcode/DerivedData/EnterpriseApp-fgrgzidhvwshopfbueiwvbkdrkwp/Build/Intermediates.noindex/ArchiveIntermediates/production/IntermediateBuildFilesPath/Pods.build/-iphoneos/RCT-Folly.build/Objects-normal/armv7/json_pointer.o /Users/runner/work/1/s/ios/Pods/RCT-Folly/folly/json_pointer.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)

### **Details**

1. Which version of the App Center SDK are you using?
    appcenter: 4.4.3
2. Which OS version did you experience the issue on?
    - iOS 12
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    -  physical device
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`

Place output here

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Place output here

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

**Comment by AnatolyPristensky** [comment]
Hello @pratius 

Described error message doesn't looks like a root cause, it also doesn't looks like an issue from the AppCenter side. I've tried to reproduce it found that all works as expected. 
Please, make sure that you are using the latest App Center SDK version (4.4.4) correctly and try to perform:

- pod cache clean --all
- pod repo update

Also, please make sure that Podfile.lock file is updated. Try to remove it, run pod install, and check if the issue is gone.
If it doesn't help - please, provide more detailed logs.

**Comment by AnatolyPristensky** [comment]
We haven't heard from you for a while, so I'm closing this issue. Please, feel free to reopen it in case of new information.
